physics_quiz/apps/classroom/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'classroom'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('classroom/', views.classroom, name='classroom'),
    path('response/', views.response, name='response'),
    path('changestatus/<post>/', views.changestatus, name='changestatus'),
    path('reset/student/', views.reset_student, name='reset_student'),
    path('view/<post>/', views.view_pdf, name='view_pdf'),
]

physics_quiz/apps/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

physics_quiz/apps/quiz/urls.py
from django.conf.urls import url

from . import views

app_name = 'quiz'

urlpatterns = [
    url(r'^survey/', views.survey, name='survey'),
    url(r'^listing/', views.listing, name='listing'),
    url(r'^statistics/', views.statistics, name='statistics'),
    url(r'^csv/', views.getfile, name='getfile')
]

physics_quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r"admin/", admin.site.urls),
    url(r"", include("physics_quiz.apps.home.urls")),
    url(r"", include("physics_quiz.apps.quiz.urls")),
    url(r"", include("physics_quiz.apps.classroom.urls")),
    url(r"", include("django.contrib.auth.urls")),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

physics_quiz/apps/home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

physics_quiz/apps/classroom/forms.py
from django import forms

class CreateForm(forms.Form):
    class_name = forms.CharField(max_length=30, required=True)
    teacher_username = forms.CharField(max_length=30, required=True)
    teacher_password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput)
    teacher_email = forms.EmailField(required=True)
    student_username = forms.CharField(max_length=30, required=True)
    student_password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput)

class SurveyForm(forms.Form):
    COLOR_CHOICES = ((1, 'red'), (2, 'blue'), (3, 'purple'), (4, 'yellow'), (5, 'green'))

    name = forms.CharField(max_length=80, required=True)
    position = forms.CharField(max_length=80, required=True)
    company = forms.CharField(max_length=80, required=True)
    location = forms.CharField(max_length=80, required=True)
    school = forms.CharField(max_length=80, required=True)
    degree = forms.CharField(max_length=80, required=True)
    experience = forms.CharField(max_length=400, required=True, widget=forms.Textarea)
    skills = forms.CharField(max_length=400, required=True, widget=forms.Textarea)
    endorsements = forms.CharField(max_length=400, required=True, widget=forms.Textarea)
    profile_pic = forms.ImageField(required=True)
    background_color = forms.ChoiceField(choices=COLOR_CHOICES, required=True)

class StudentResetForm(forms.Form):
    new_password1 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput)
    new_password2 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput)

    def is_valid(self):
        valid = super(StudentResetForm, self).is_valid()
        return self.cleaned_data["new_password1"] == self.cleaned_data["new_password2"]

physics_quiz/apps/classroom/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.core.files import File
from django.core.files.storage import default_storage
from django.conf import settings
from django.template.loader import render_to_string

from .forms import CreateForm, SurveyForm, StudentResetForm
from .models import Classes, Post

from weasyprint import HTML
from slugify import slugify
import tempfile

def create(request):
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            class_name = slugify(form.cleaned_data['class_name'])

            # check
            repeat_c = False
            repeat_t = False
            repeat_s = False
            repeat = False
            current_users = User.objects.all()
            for t in current_users:
                if t.username == form.cleaned_data['teacher_username']:
                    repeat_t = True
                if t.username == form.cleaned_data['student_username']:
                    repeat_s = True
            current_classes = Classes.objects.all()
            for c in current_classes:
                if c.name == class_name:
                    repeat_c = True
            if form.cleaned_data['teacher_username'] == form.cleaned_data["student_username"]:
                repeat = True
            if repeat_c or repeat_s or repeat_t or repeat:
                return render(request, 'classroom/create.html', context={'form':form, 'repeat_c':repeat_c, 'repeat_t':repeat_t, 'repeat_s':repeat_s, 'repeat':repeat})

            # create class
            new_teacher = User.objects.create_user(form.cleaned_data['teacher_username'], form.cleaned_data['teacher_email'], form.cleaned_data['teacher_password'])
            new_teacher.groups.add(Group.objects.get(name="teacher"))
            new_teacher.save()
            new_student = User.objects.create_user(form.cleaned_data['student_username'], "", form.cleaned_data['student_password'])
            new_student.groups.add(Group.objects.get(name="student"))
            new_student.save()
            new_class = Classes(name=class_name, teacher=new_teacher, student=new_student)
            new_class.save()
            return HttpResponseRedirect(reverse('classroom:classroom'))
        return render(request, 'classroom/create.html', context={'form':form})
    else:
        form = CreateForm()
        return render(request, 'classroom/create.html', context={'form':form})

@login_required
def reset_student(request):
    user = request.user
    if user.groups.filter(name="teacher").exists():
        if request.method == "POST":
            form = StudentResetForm(request.POST)
            if form.is_valid():
                student = user.class_teacher.student
                student.set_password(form.cleaned_data['new_password1'])
                student.save()
                return render(request, "registration/password_reset_complete.html", context={})
            return render(request, "classroom/password_reset.html", context={'form':form})
        else:
            form = StudentResetForm()
            return render(request, "classroom/password_reset.html", context={'form':form})
    else:
        return HttpResponse("You are not authorized to access this page.")

@login_required
def response(request):
    user = request.user
    classname = ""
    if user.groups.filter(name='student').exists():
        classname = user.class_student
    elif user.groups.filter(name='teacher').exists():
        classname = user.class_teacher
    else:  # user is trying to access as staff or superuser
        return HttpResponse("You are trying to access this page as a superuser or administrator. Please login as a teacher or student.")
    if request.method == 'POST':
        form = SurveyForm(request.POST, request.FILES)
        if form.is_valid():
            find_class = Classes.objects.get(name=classname)

            new_id = slugify(form.cleaned_data['name'] + form.cleaned_data['position'] + form.cleaned_data['location'])
            new_id = new_id[:40]
            
            colors = ["red", "blue", "purple", "yellow", "green"]

            new_post = Post(
                name=form.cleaned_data['name'],
                post_id=new_id,
                classes=find_class,
                profile_pic=form.cleaned_data['profile_pic'],
                position=form.cleaned_data['position'],
                company=form.cleaned_data['company'],
                location=form.cleaned_data['location'],
                school=form.cleaned_data['school'],
                degree=form.cleaned_data['degree'],
                experience=form.cleaned_data['experience'],
                skills=form.cleaned_data['skills'],
                endorsements=form.cleaned_data['endorsements'],
                background_color=colors[int(form.cleaned_data["background_color"]) + 1],
            )
            new_post.save()

            return HttpResponseRedirect(reverse('classroom:classroom'))
        return render(request, 'classroom/survey.html', context={'form':form, 'error': True})
    else:
        form = SurveyForm()
        return render(request, 'classroom/survey.html', context={'form':form})

@login_required
def classroom(request):
    user = request.user
    person = ""
    classname = ""
    if user.groups.filter(name='student').exists():
        classname = user.class_student
        person = "student"
    elif user.groups.filter(name='teacher').exists():
        classname = user.class_teacher
        person = "teacher"
    else:  # user is trying to access as staff or superuser
        return HttpResponse("You are trying to access this page as a superuser or administrator. Please login as a teacher or student.")
    post_list = Post.objects.filter(classes=Classes.objects.get(name=classname))
    if person == 'teacher':
        return render(request, 'classroom/classroom.html', context={'post_list':post_list, "person": person})
    elif person == 'student':
        show_post_list = list()
        for item in post_list:
            if item.hidden == False:
                show_post_list.append(item)
        return render(request, 'classroom/classroom.html', context={'post_list':show_post_list, "person": person})

@login_required
def changestatus(request, post):
    to_change = Post.objects.get(post_id=str(post))
    to_change.changeStatus()
    return HttpResponseRedirect(reverse('classroom:classroom'))

@login_required
def view_pdf(request, post):
    post = Post.objects.get(post_id=post)
    html_string = render_to_string('profile_template.html', {
        'name': post.name,
        'position': post.position,
        'company': post.company,
        'location': post.location,
        'school': post.school,
        'degree': post.degree,
        'experience': post.experience,
        'skills': post.skills,
        'endorsements': post.endorsements,
        'profile_pic': post.profile_pic,
        'color': post.background_color,
        })
    
    pdf = HTML(string=html_string).write_pdf()

    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'attachment; filename=student_profile.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(pdf)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())

    return response

physics_quiz/apps/home/views.py
from django.shortcuts import render
from django.core.mail import send_mail

def index(request):
    return render(request, 'home/index.html')

physics_quiz/apps/quiz/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required

from .forms import QuizForm
from .models import Profile, Option, Answer

import random
import csv

def survey(request):
    if request.method == 'POST':
        form = QuizForm(request.POST)
        if form.is_valid():
            q1_ans, q2_ans = form.process()

            if form.cleaned_data['question_type'] == '0':  # if the user is a student
                # update backend info
                for ans in q1_ans:
                    for related in q1_ans:
                        opt = Option.objects.get(name=str(ans))
                        opt.increment(str(related))
                    for related in q2_ans:
                        opt = Option.objects.get(name=str(ans))
                        opt.increment(str(related))
                for ans in q2_ans:
                    for related in q1_ans:
                        opt = Option.objects.get(name=str(ans))
                        opt.increment(str(related))
                    for related in q2_ans:
                        opt = Option.objects.get(name=str(ans))
                        opt.increment(str(related))
                
                # update for csv file
                back_dict = {'1':'Making money', '2':'Helping other people', '3': 'Having job security', '4': 'Working with people', '5': 'Having lots of family time', '6': 'Having an exciting job', '7': 'Making use of my talents/abilities', 'a': 'Medicine/Health', 'b': 'Biology', 'c': 'Chemistry', 'd': 'Physics', 'e': 'Astronomy', 'f': 'Engineering', 'g': 'English/Writing', 'h': 'Finance/Business/Consultancy', 'i': 'Administration/Management', 'j': 'Arts/Media', 'k': 'Academia/Education', 'l': 'Technology/Computer Science', 'm': 'Law'}
                new_ans = Answer(ans=back_dict[str(q1_ans[0])] + ',' + back_dict[str(q1_ans[1])] + ',' + back_dict[str(q1_ans[2])] + ',' + back_dict[str(q2_ans[0])] + ',' + back_dict[str(q2_ans[1])])
                new_ans.save()
            
            # calculate results
            ans_dict = {}
            score_dict = {}
            for profile in Profile.objects.filter(Q(q2_answer=q2_ans[0]) | Q(q2_answer=q2_ans[1])):
                ans_dict.update({profile: profile.q1_convert()})
                score_dict.update({profile: 0})
            for num in q1_ans:
                for profile in ans_dict:
                    if str(num) in ans_dict[profile]:
                        score_dict[profile] += 1
            unordered_list = list()
            for profile in score_dict:
                unordered_list.append((score_dict[profile], profile))
            ordered_list = sorted(unordered_list, key=lambda score: score[0], reverse=True)
            final_ordered_list = list()
            count = 0
            for item in ordered_list:
                if count < 6:
                    final_ordered_list.append(item[1])
                    count += 1
            for n in range(0, len(q2_ans)):
                q2_ans[n] = str(q2_ans[n])
            tag_list = list()
            ans_list = list()
            ans_list.append(q1_ans[0]); ans_list.append(q1_ans[1]); ans_list.append(q1_ans[2]); ans_list.append(q2_ans[0]); ans_list.append(q2_ans[1])
            for profile in final_ordered_list:
                tag_list.append((profile, ', '.join(profile.compare_ans(ans_list))))
            
            # return
            return render(request, 'quiz/results.html', context={'profiles':tag_list})
        return render(request, 'quiz/questions.html', context={'form':form})
    else:
        form = QuizForm()
        return render(request, 'quiz/questions.html', context={'form':form})

def listing(request):
    profiles = list()
    for p in Profile.objects.all():
        profiles.append(p)
    random.shuffle(profiles)
    return render(request, 'quiz/list.html', context={'profiles':profiles})

@login_required
def statistics(request):
    user = request.user
    if user.username == "site_superuser" or user.username == "site_staff" or user.is_superuser:
        opts = Option.objects.all()
        if request.method == 'POST':
            for o in opts:
                o.reset()
            answers = Answer.objects.all()
            for a in answers:
                a.delete()
            return HttpResponseRedirect(reverse('quiz:statistics'))
        else:
            # count self
            self_counts_q1 = list()
            self_counts_q2 = list()
            num = 0
            for o in opts:
                if o.name.isalpha():
                    self_counts_q1.append(o.self_count(o.name))
                else:
                    self_counts_q2.append(o.self_count(o.name))
                num += 1

            ctx = {'self_counts_q1':self_counts_q1, 'self_counts_q2':self_counts_q2}
            return render(request, 'quiz/stats.html', context=ctx)
    else:
        return HttpResponse("You are not authorized to view this page.")

@login_required
def getfile(request):
    user = request.user
    if user.username == "site_superuser" or user.username == "site_staff":
        response = HttpResponse(content_type='text/csv')  
        response['Content-Disposition'] = 'attachment; filename="answer_stats.csv"'
        writer = csv.writer(response)
        for a in Answer.objects.all():
            new_list = a.ans.split(', ')
            writer.writerow(new_list) 
        return response
    else:
        return HttpResponse("You are not authorized to view this page.")

physics_quiz/templates/classroom/classroom.html
{% extends "base_with_head.html" %}

{% load static %}

{% block head %}
    <link rel='stylesheet' href="{% static 'css/classroom.css' %}">
{% endblock %}

{% block main %}
    {% if person == "teacher" %}
        <p>The profiles from your students will appear below and you will have the option to make them available for students to see.</p>
        <hr>
        {% for item in post_list %}
            <div class="row">
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                    <a href="{% url 'classroom:view_pdf' item.post_id %}" target="_blank" class='post'>{{ item.name }}'s Profile</a>                          
                </div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                    {% if item.hidden == True %}
                        <a href="{% url 'classroom:changestatus' item.post_id %}"><button class='aps-btn'>Post to Students</button></a>
                    {% endif %}
                    {% if item.hidden == False %}
                        <a href="{% url 'classroom:changestatus' item.post_id %}"><button class='aps-btn'>Hide from Students</button></a>
                    {% endif %}
                </div>
            </div>
            <hr>
        {% endfor %}
        <div class="centered-div">
            <a href="{% url 'classroom:reset_student' %}"><button class='aps-btn'>Reset Student Password</button></a>
        </div>
    {% endif %}
    {% if person == "student" %}
        <div class="centered-div">
            <a href="{% url 'classroom:response' %}"><button class='aps-btn'>Create Profile</button></a>
        </div>
        <hr>
        <p>The profiles from your fellow classmates will appear below as your teacher makes them available.</p>
        <hr>
        {% for item in post_list %}
            <a href="{% url 'classroom:view_pdf' item.post_id %}" target="_blank" class='post'>{{ item.name }}'s Profile</a>                          
            <hr>
        {% endfor %}
    {% endif %}
{% endblock %}

physics_quiz/templates/classroom/create.html
{% extends "base_with_head.html" %}

{% load static %}

{% block head %}
    <link rel='stylesheet' href="{% static 'css/classroom.css' %}">
{% endblock %}

{% block main %}
    <form action='' method='post'>
        {% csrf_token %}
        <p>Class name:  {{ form.class_name }}</p>
        {% if repeat_c %}
            <p class='error'>This class name is already in use.</p>
        {% endif %}
        <p>Teacher username:  {{ form.teacher_username }}</p>
        <p>Teacher password:  {{ form.teacher_password }}</p>
        <p>Teacher email:  {{ form.teacher_email }}</p>
        {% if repeat_t %}
            <p class='error'>This teacher username is already in use.</p>
        {% endif %}
        <p>Student username:  {{ form.student_username }}</p>
        <p>Student password:  {{ form.student_password }}</p>
        {% if repeat_s %}
            <p class='error'>This student username is already in use.</p>
        {% endif %}
        {% if repeat %}
            <p class='error'>The student and teacher usernames cannot be the same.</p>
        {% endif %}
        <div class="centered-div">
            <input class='aps-btn' type='submit' name='Submit' value='Create Class'/>
        </div>
    </form>
{% endblock %}

physics_quiz/templates/classroom/password_reset.html
{% extends "base_with_head.html" %}

{% load static %}

{% block head %}
    <link rel='stylesheet' href="{% static 'css/classroom.css' %}">
{% endblock %}

{% block main %}
    <p>Please enter (and confirm) the new password for your student to use.</p>
    <form action="" method="post">
    {% csrf_token %}
        <table>
            <tr>
                <td><p class="error">{{ form.new_password1.errors }}</p>
                    <label for="id_new_password1">New password:</label></td>
                <td>{{ form.new_password1 }}</td>
            </tr>
            <tr>
                <td><p class="error">{{ form.new_password2.errors }}</p>
                    <label for="id_new_password2">Confirm password:</label></td>
                <td>{{ form.new_password2 }}</td>
            </tr>
            <tr>
                <td></td>
                <td><input class="aps-btn" type="submit" value="Change my password" name="Change my password"/></td>
            </tr>
        </table>
    </form>
{% endblock %}

physics_quiz/templates/classroom/survey.html
{% extends "base_with_head.html" %}

{% load static %}

{% block head %}
    <link rel='stylesheet' href="{% static 'css/classroom.css' %}">
{% endblock %}

{% block main %}
    <form action='' method='post' enctype="multipart/form-data">
        {% csrf_token %}
        <p>Name:  {{ form.name }}</p>
        <p>Company:  {{ form.company }}</p>
        <p>Position:  {{ form.position }}</p>
        <p>Profile Picture:  {{ form.profile_pic }}</p>
        <p>Background Color:  {{ form.background_color }}</p>
        <p>Work Location:  {{ form.location }}</p>
        <p>College:  {{ form.school }}</p>
        <p>Degree:  {{ form.degree }}</p>
        <p>Experience:  {{ form.experience }}</p>
        <p>Skills:  {{ form.skills }}</p>
        <p>Endorsements:  {{ form.endorsements }}</p>
        <div class="centered-div">
            <input class='aps-btn' type='submit' name='Submit' value='Submit'/> 
        </div>
    </form>
    {% if error %}
        <p class='error'>{{ form.errors }}</p>
    {% endif %}
{% endblock %}