physics_quiz/apps/classroom/urls.py
from django.conf.urls import url
from django.urls import path

from . import views

app_name = 'classroom'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('classroom/', views.classroom, name='classroom'),
    path('response/', views.response, name='response'),
    path('changestatus/<post>/', views.changestatus, name='changestatus'),
    path('reset/student/', views.reset_student, name='reset_student'),
    path('view/<post>/', views.view_pdf, name='view_pdf'),
]

physics_quiz/apps/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

physics_quiz/apps/quiz/urls.py
from django.conf.urls import url

from . import views

app_name = 'quiz'

urlpatterns = [
    url(r'^survey/', views.survey, name='survey'),
    url(r'^listing/', views.listing, name='listing'),
    url(r'^statistics/', views.statistics, name='statistics'),
    url(r'^csv/', views.getfile, name='getfile')
]

physics_quiz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r"admin/", admin.site.urls),
    url(r"", include("physics_quiz.apps.home.urls")),
    url(r"", include("physics_quiz.apps.quiz.urls")),
    url(r"", include("physics_quiz.apps.classroom.urls")),
    url(r"", include("django.contrib.auth.urls")),
]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

physics_quiz/apps/home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

physics_quiz/apps/classroom/forms.py
from django import forms

class CreateForm(forms.Form):
    class_name = forms.CharField(max_length=30, required=True)
    teacher_username = forms.CharField(max_length=30, required=True)
    teacher_password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput)
    teacher_email = forms.EmailField(required=True)
    student_username = forms.CharField(max_length=30, required=True)
    student_password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput)

class SurveyForm(forms.Form):
    COLOR_CHOICES = ((1, 'red'), (2, 'blue'), (3, 'purple'), (4, 'yellow'), (5, 'green'))

    name = forms.CharField(max_length=80, required=True)
    position = forms.CharField(max_length=80, required=True)
    company = forms.CharField(max_length=80, required=True)
    location = forms.CharField(max_length=80, required=True)
    school = forms.CharField(max_length=80, required=True)
    degree = forms.CharField(max_length=80, required=True)
    experience = forms.CharField(max_length=400, required=True, widget=forms.Textarea)
    skills = forms.CharField(max_length=400, required=True, widget=forms.Textarea)
    endorsements = forms.CharField(max_length=400, required=True, widget=forms.Textarea)
    profile_pic = forms.ImageField(required=True)
    background_color = forms.ChoiceField(choices=COLOR_CHOICES, required=True)

class StudentResetForm(forms.Form):
    new_password1 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput)
    new_password2 = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput)

    def is_valid(self):
        valid = super(StudentResetForm, self).is_valid()
        return self.cleaned_data["new_password1"] == self.cleaned_data["new_password2"]

physics_quiz/apps/classroom/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.core.files import File
from django.core.files.storage import default_storage
from django.conf import settings
from django.template.loader import render_to_string

from .forms import CreateForm, SurveyForm, StudentResetForm
from .models import Classes, Post

from weasyprint import HTML
from slugify import slugify
import tempfile

def create(request):
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            class_name = slugify(form.cleaned_data['class_name'])

            # check
            repeat_c = False
            repeat_t = False
            repeat_s = False
            repeat = False
            current_users = User.objects.all()
            for t in current_users:
                if t.username == form.cleaned_data['teacher_username']:
                    repeat_t = True
                if t.username == form.cleaned_data['student_username']:
                    repeat_s = True
            current_classes = Classes.objects.all()
            for c in current_classes:
                if c.name == class_name:
                    repeat_c = True
            if form.cleaned_data['teacher_username'] == form.cleaned_data["student_username"]:
                repeat = True
            if repeat_c or repeat_s or repeat_t or repeat:
                return render(request, 'classroom/create.html', context={'form':form, 'repeat_c':repeat_c, 'repeat_t':repeat_t, 'repeat_s':repeat_s, 'repeat':repeat})

            # create class
            new_teacher = User.objects.create_user(form.cleaned_data['teacher_username'], form.cleaned_data['teacher_email'], form.cleaned_data['teacher_password'])
            new_teacher.groups.add(Group.objects.get(name="teacher"))
            new_teacher.save()
            new_student = User.objects.create_user(form.cleaned_data['student_username'], "", form.cleaned_data['student_password'])
            new_student.groups.add(Group.objects.get(name="student"))
            new_student.save()
            new_class = Classes(name=class_name, teacher=new_teacher, student=new_student)
            new_class.save()
            return HttpResponseRedirect(reverse('classroom:classroom'))
        return render(request, 'classroom/create.html', context={'form':form})
    else:
        form = CreateForm()
        return render(request, 'classroom/create.html', context={'form':form})

@login_required
def reset_student(request):
    user = request.user
    if user.groups.filter(name="teacher").exists():
        if request.method == "POST":
            form = StudentResetForm(request.POST)
            if form.is_valid():
                student = user.class_teacher.student
                student.set_password(form.cleaned_data['new_password1'])
                student.save()
                return render(request, "registration/password_reset_complete.html", context={})
            return render(request, "classroom/password_reset.html", context={'form':form})
        else:
            form = StudentResetForm()
            return render(request, "classroom/password_reset.html", context={'form':form})
    else:
        return HttpResponse("You are not authorized to access this page.")

@login_required
def response(request):
    user = request.user
    classname = ""
    if user.groups.filter(name='student').exists():
        classname = user.class_student
    elif user.groups.filter(name='teacher').exists():
        classname = user.class_teacher
    else:  # user is trying to access as staff or superuser
        return HttpResponse("You are trying to access this page as a superuser or administrator. Please login as a teacher or student.")
    if request.method == 'POST':
        form = SurveyForm(request.POST, request.FILES)
        if form.is_valid():
            find_class = Classes.objects.get(name=classname)

            new_id = slugify(form.cleaned_data['name'] + form.cleaned_data['position'] + form.cleaned_data['location'])
            new_id = new_id[:40]
            
            colors = ["red", "blue", "purple", "yellow", "green"]

            new_post = Post(
                name=form.cleaned_data['name'],
                post_id=new_id,
                classes=find_class,
                profile_pic=form.cleaned_data['profile_pic'],
                position=form.cleaned_data['position'],
                company=form.cleaned_data['company'],
                location=form.cleaned_data['location'],
                school=form.cleaned_data['school'],
                degree=form.cleaned_data['degree'],
                experience=form.cleaned_data['experience'],
                skills=form.cleaned_data['skills'],
                endorsements=form.cleaned_data['endorsements'],
                background_color=colors[int(form.cleaned_data["background_color"]) + 1],
            )
            new_post.save()

            return HttpResponseRedirect(reverse('classroom:classroom'))
        return render(request, 'classroom/survey.html', context={'form':form, 'error': True})
    else:
        form = SurveyForm()
        return render(request, 'classroom/survey.html', context={'form':form})

@login_required
def classroom(request):
    user = request.user
    person = ""
    classname = ""
    if user.groups.filter(name='student').exists():
        classname = user.class_student
        person = "student"
    elif user.groups.filter(name='teacher').exists():
        classname = user.class_teacher
        person = "teacher"
    else:  # user is trying to access as staff or superuser
        return HttpResponse("You are trying to access this page as a superuser or administrator. Please login as a teacher or student.")
    post_list = Post.objects.filter(classes=Classes.objects.get(name=classname))
    if person == 'teacher':
        return render(request, 'classroom/classroom.html', context={'post_list':post_list, "person": person})
    elif person == 'student':
        show_post_list = list()
        for item in post_list:
            if item.hidden == False:
                show_post_list.append(item)
        return render(request, 'classroom/classroom.html', context={'post_list':show_post_list, "person": person})

@login_required
def changestatus(request, post):
    to_change = Post.objects.get(post_id=str(post))
    to_change.changeStatus()
    return HttpResponseRedirect(reverse('classroom:classroom'))

@login_required
def view_pdf(request, post):
    post = Post.objects.get(post_id=post)
    html_string = render_to_string('profile_template.html', {
        'name': post.name,
        'position': post.position,
        'company': post.company,
        'location': post.location,
        'school': post.school,
        'degree': post.degree,
        'experience': post.experience,
        'skills': post.skills,
        'endorsements': post.endorsements,
        'profile_pic': post.profile_pic,
        'color': post.background_color,
        })
    
    pdf = HTML(string=html_string).write_pdf()

    response = HttpResponse(content_type='application/pdf;')
    response['Content-Disposition'] = 'attachment; filename=student_profile.pdf'
    response['Content-Transfer-Encoding'] = 'binary'
    with tempfile.NamedTemporaryFile(delete=True) as output:
        output.write(pdf)
        output.flush()
        output = open(output.name, 'rb')
        response.write(output.read())

    return response

physics_quiz/apps/home/views.py
from django.shortcuts import render
from django.core.mail import send_mail

def index(request):
    return render(request, 'home/index.html')

physics_quiz/apps/quiz/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth.decorators import login_required, permission_required

from .forms import QuizForm
from .models import Profile, Option, Answer

import random
import csv

def survey(request):
    if request.method == 'POST':
        form = QuizForm(request.POST)
        if form.is_valid():
            q1_ans, q2_ans = form.process()

            if form.cleaned_data['question_type'] == '0':  # if the user is a student
                # update backend info
                for ans in q1_ans:
                    for related in q1_ans:
                        opt = Option.objects.get(name=str(ans))
                        opt.increment(str(related))
                    for related in q2_ans:
                        opt = Option.objects.get(name=str(ans))
                        opt.increment(str(related))
                for ans in q2_ans:
                    for related in q1_ans:
                        opt = Option.objects.get(name=str(ans))
                        opt.increment(str(related))
                    for related in q2_ans:
                        opt = Option.objects.get(name=str(ans))
                        opt.increment(str(related))
                
                # update for csv file
                back_dict = {'1':'Making money', '2':'Helping other people', '3': 'Having job security', '4': 'Working with people', '5': 'Having lots of family time', '6': 'Having an exciting job', '7': 'Making use of my talents/abilities', 'a': 'Medicine/Health', 'b': 'Biology', 'c': 'Chemistry', 'd': 'Physics', 'e': 'Astronomy', 'f': 'Engineering', 'g': 'English/Writing', 'h': 'Finance/Business/Consultancy', 'i': 'Administration/Management', 'j': 'Arts/Media', 'k': 'Academia/Education', 'l': 'Technology/Computer Science', 'm': 'Law'}
                new_ans = Answer(ans=back_dict[str(q1_ans[0])] + ',' + back_dict[str(q1_ans[1])] + ',' + back_dict[str(q1_ans[2])] + ',' + back_dict[str(q2_ans[0])] + ',' + back_dict[str(q2_ans[1])])
                new_ans.save()
            
            # calculate results
            ans_dict = {}
            score_dict = {}
            for profile in Profile.objects.filter(Q(q2_answer=q2_ans[0]) | Q(q2_answer=q2_ans[1])):
                ans_dict.update({profile: profile.q1_convert()})
                score_dict.update({profile: 0})
            for num in q1_ans:
                for profile in ans_dict:
                    if str(num) in ans_dict[profile]:
                        score_dict[profile] += 1
            unordered_list = list()
            for profile in score_dict:
                unordered_list.append((score_dict[profile], profile))
            ordered_list = sorted(unordered_list, key=lambda score: score[0], reverse=True)
            final_ordered_list = list()
            count = 0
            for item in ordered_list:
                if count < 6:
                    final_ordered_list.append(item[1])
                    count += 1
            for n in range(0, len(q2_ans)):
                q2_ans[n] = str(q2_ans[n])
            tag_list = list()
            ans_list = list()
            ans_list.append(q1_ans[0]); ans_list.append(q1_ans[1]); ans_list.append(q1_ans[2]); ans_list.append(q2_ans[0]); ans_list.append(q2_ans[1])
            for profile in final_ordered_list:
                tag_list.append((profile, ', '.join(profile.compare_ans(ans_list))))
            
            # return
            return render(request, 'quiz/results.html', context={'profiles':tag_list})
        return render(request, 'quiz/questions.html', context={'form':form})
    else:
        form = QuizForm()
        return render(request, 'quiz/questions.html', context={'form':form})

def listing(request):
    profiles = list()
    for p in Profile.objects.all():
        profiles.append(p)
    random.shuffle(profiles)
    return render(request, 'quiz/list.html', context={'profiles':profiles})

@login_required
def statistics(request):
    user = request.user
    if user.username == "site_superuser" or user.username == "site_staff" or user.is_superuser:
        opts = Option.objects.all()
        if request.method == 'POST':
            for o in opts:
                o.reset()
            answers = Answer.objects.all()
            for a in answers:
                a.delete()
            return HttpResponseRedirect(reverse('quiz:statistics'))
        else:
            # count self
            self_counts_q1 = list()
            self_counts_q2 = list()
            num = 0
            for o in opts:
                if o.name.isalpha():
                    self_counts_q1.append(o.self_count(o.name))
                else:
                    self_counts_q2.append(o.self_count(o.name))
                num += 1

            ctx = {'self_counts_q1':self_counts_q1, 'self_counts_q2':self_counts_q2}
            return render(request, 'quiz/stats.html', context=ctx)
    else:
        return HttpResponse("You are not authorized to view this page.")

@login_required
def getfile(request):
    user = request.user
    if user.username == "site_superuser" or user.username == "site_staff":
        response = HttpResponse(content_type='text/csv')  
        response['Content-Disposition'] = 'attachment; filename="answer_stats.csv"'
        writer = csv.writer(response)
        for a in Answer.objects.all():
            new_list = a.ans.split(', ')
            writer.writerow(new_list) 
        return response
    else:
        return HttpResponse("You are not authorized to view this page.")

physics_quiz/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang='en'>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>Lessons - Step Up</title>
        <meta name='author' content='Lauren Delwiche'>
        <link rel="icon" href="{% static 'img/fav-logo.png' %}">

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/74f5f903f7.js" crossorigin="anonymous"></script>

        <link rel='stylesheet' href="{% static 'css/base.css' %}">
        <link rel='stylesheet' href="{% static 'css/nav.css' %}">
        <link rel='stylesheet' href="{% static 'css/foot.css' %}">

        {% block head %}{% endblock %}
    </head>
    <body>
        {% block root %}
            {% block main %}
            {% endblock %}
        {% endblock %}
    </body>
</html>

physics_quiz/templates/base_with_head.html
{% extends 'base.html' %}

{% load static %}

{% block root %}
    <div class='header'>
        <div class="header-back"></div>
        <div class="brand">
            <a href="{% url 'home:index' %}"><img class="head-logo" src="https://higherlogicdownload.s3.amazonaws.com/APS/2c0c9f07-6428-4f8e-b9aa-a76098a80cd0/UploadedImages/logo-stepup.svg"/></a>
        </div>
        <div class="btn-bar row">
            <a href="{% url 'quiz:listing' %}" class="nav-item">Profiles</a>
            <a href="{% url 'quiz:survey' %}" class="nav-item">Survey</a>
            <a href="{% url 'classroom:classroom' %}" class="nav-item">Classroom</a>
            <div class="dropdown nav-item">
                <button class="btn dropdown-toggle user-item" data-toggle="dropdown">
                    <i class="fas fa-user"></i>
                    <span class="caret"></span>
                </button>
                <div class="dropdown-menu dropdown-menu-right drop-item">
                    {% if user.is_authenticated %}
                        <ul>{{ user.username }}</ul>
                        {% with class_name=user.groups.all.0|stringformat:"s" %}
                            {% if class_name == "teacher" %}
                                <ul><a href="{% url 'classroom:classroom' %}" class="drop-item">{{ user.class_teacher }}</a></ul>
                            {% elif class_name == "student" %}
                                <ul><a href="{% url 'classroom:classroom' %}" class="drop-item">{{ user.class_student }}</a></ul>
                            {% else %}
                                <ul><a href="#" class="drop-item">No Class</a></ul>
                            {% endif %}
                        {% endwith %}
                        <ul><a href="{% url 'logout' %}" class="drop-item">Logout</a></ul>
                    {% else %}
                        <ul><a href="{% url 'login' %}" class="drop-item">Login</a></ul>
                    {% endif %}
                </div>
            </div>
        </div>               
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <div class="height-holder"></div>

    <div style="margin: 20px;">
        {% block main %}{% endblock %}
    </div>

    <div class="height-holder"></div>

    <div class='footer'>
        <div class="logo-col">
            <img class="light-logo" src="https://higherlogicdownload.s3.amazonaws.com/APS/2c0c9f07-6428-4f8e-b9aa-a76098a80cd0/UploadedImages/logo-stepup-light.svg">
            <br>
            <br>
            <p>Follow Us</p>
            <div>
                <a href="https://www.facebook.com/STEPUPPhysics/"><img class="social-icon" src="{% static 'img/facebook.png' %}" /></a>
                <a href="https://www.instagram.com/stepupphysics/"><img class="social-icon" src="{% static 'img/instagram.png' %}" /></a>
                <a href="https://twitter.com/STEPUPphysics"><img class="social-icon" src="{% static 'img/twitter.png' %}" /></a>
            </div>
            <br>
            <br>
            <p>Created by <a class="credit" href='https://www.linkedin.com/in/lauren-delwiche-518638197'>Lauren Delwiche</a></p>
        </div>
    </div>
{% endblock %}

physics_quiz/templates/profile_template.html
<html>
    <head>
        <meta charset="utf-8">
        <link href="profile_template.css" rel="stylesheet">
        <style>
            @page {
                size: Letter;
                margin: 1cm;
            }
            html {
            color: #393939;
            font-size: 11pt;
            font-weight: 300;
            line-height: 1.5; 
            }
            html body h1 {
                color: #fbc847;
                font-size: 38pt;
                margin: 0 2cm 0 2cm;
                width: 100%; 
            }
            html body h2, html body h3, html body h4 {
                color: black;
                font-weight: 400; 
            }
            html body h2 {
                break-before: always;
                font-size: 28pt; 
            }
            html body img {
                break-before: always;
                max-height: 6cm;
                text-align: center;
                border-radius: 50%;
                margin-bottom: .5cm;
            }
            html body h3 {
                font-weight: 300;
                font-size: 15pt; 
            }
            html body h4 {
                font-size: 13pt; 
            }
            html body article#competences h3 {
                background: {{ color }};
                margin: 0 -3cm 1cm;
                padding: 1cm 1cm 1cm 3cm;
                width: 21cm; 
            }
            html body article#competences section {
                padding: .2cm 0;
                min-height: 2.3cm;
            }
            html body article#competences section h4 {
                margin: 0; 
            }
            html body article#competences section p {
                margin-top: 0; 
            }
            html body article#competences section#education::before {
                background: no-repeat center {{ color }};
                background-size: 50%;
                content: '';
                display: inline-block;
                float: left;
                height: 2cm;
                margin-right: .5cm;
                vertical-align: middle;
                width: 2cm; 
            }
            html body article#competences section#experience::before {
                background: no-repeat center {{ color }};
                background-size: 50%;
                content: '';
                display: inline-block;
                float: left;
                height: 2cm;
                margin-right: .5cm;
                vertical-align: middle;
                width: 2cm; 
            }
            html body article#competences section#skills::before {
                background: no-repeat center {{ color }};
                background-size: 50%;
                content: '';
                display: inline-block;
                float: left;
                height: 2cm;
                margin-right: .5cm;
                vertical-align: middle;
                width: 2cm; 
            }
            html body article#competences section#endorsements::before {
                background: no-repeat center {{ color }};
                background-size: 50%;
                content: '';
                display: inline-block;
                float: left;
                height: 2cm;
                margin-right: .5cm;
                vertical-align: middle;
                width: 2cm; 
            }
        </style>
    </head>

    <body>
        <article id="competences">
            <div style="text-align:center;">
                <img src="{{ profile_pic.url }}" />
            </div>

            <h3 style="background:{{ color }};">
                <b>{{ name }}</b>
                <br>
                {{ position }} at {{ company }}
                <br>
                {{ location }}
            </h3>

            <section id="education">
                <h4>Education:</h4>
                <p>
                {{ degree }} from {{ school }}
                </p>
            </section>

            <section id="experience">
                <h4>Experience:</h4>
                <p>
                {{ experience }}
                </p>
            </section>

            <section id="skills">
                <h4>Skills:</h4>
                <p>
                {{ skills }}
                </p>
            </section>

            <section id="endorsements">
                <h4>Endorsements:</h4>
                <p>
                {{ endorsements }}
                </p>
            </section>
        </article>
    </body>
</html>